import dotenv from "dotenv";
export const dotEnvConfig = {path: '.env.local'}
dotenv.config(dotEnvConfig);
export const {
    MONGO_DB_URL,
    API_URL,
    FRONTEND_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL,
    WITHINGS_CLIENT_ID,
    WITHINGS_CLIENT_SECRET,
    WITHINGS_CALLBACK_URL,
    AGENT_API_KEY,
    JWT_SECRET,
    JWT_REFRESH_SECRET,
    NODE_ENV,
    ASTERISK_AMI_HOST,
    ASTERISK_AMI_PORT,
    ASTERISK_AMI_USERNAME,
    ASTERISK_AMI_PASSWORD,
    // PostgreSQL for telecare/PJSIP realtime
    POSTGRES_HOST,
    POSTGRES_PORT,
    POSTGRES_DATABASE,
    POSTGRES_USER,
    POSTGRES_PASSWORD
} = process.env;

console.log('Environment Variables:', {
    MONGO_DB_URL,
    API_URL,
    FRONTEND_URL,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL,
    WITHINGS_CLIENT_ID,
    WITHINGS_CLIENT_SECRET,
    WITHINGS_CALLBACK_URL,
    AGENT_API_KEY,
    JWT_SECRET: JWT_SECRET ? '[SET]' : '[NOT SET]',
    JWT_REFRESH_SECRET: JWT_REFRESH_SECRET ? '[SET]' : '[NOT SET]',
    NODE_ENV,
    ASTERISK_AMI_HOST,
    ASTERISK_AMI_PORT,
    ASTERISK_AMI_USERNAME,
    ASTERISK_AMI_PASSWORD: ASTERISK_AMI_PASSWORD ? '[SET]' : '[NOT SET]',
    POSTGRES_HOST,
    POSTGRES_PORT,
    POSTGRES_DATABASE,
    POSTGRES_USER,
    POSTGRES_PASSWORD: POSTGRES_PASSWORD ? '[SET]' : '[NOT SET]'
})